config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'
  devise_for :users

  resources :weather_dashboards, only: %i[index new create destroy] do
    get '/update_state_options', to: "weather_dashboards#update_state_options", on: :collection
    get '/update_city_options', to: "weather_dashboards#update_city_options", on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :weather_dashboards
end

app/models/weather_dashboard.rb
class WeatherDashboard < ApplicationRecord
  belongs_to :user

  validates :country, :city, :state, presence: true
  validates :forecast_days, inclusion: { in: 1..7 }
  validate :verify_similar_weather_cards_should_not_exist?

  scope :city_names_and_days, ->(user_id){ where(user_id: user_id).pluck(:city, :forecast_days) }

  private

  def verify_similar_weather_cards_should_not_exist?
    if self.class.where(user_id: user_id, country: country, city: city).exists?
      errors.add(:base, "Weather card with city: #{city}, already added.")
    end

    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    redirect_to weather_dashboards_path and return if user_signed_in?
  end
end

app/controllers/weather_dashboards_controller.rb
class WeatherDashboardsController < ApplicationController
  def index
    city_names_days = WeatherDashboard.city_names_and_days(current_user.id)

    @all_cities_weather = {}
    city_names_days.each  do |sub_array|
      @all_cities_weather[sub_array[0]] = WeatherApi::GetWeatherData.new(city: sub_array[0], days: sub_array[1]).call
    end
  end

  def new
    @weather_dashboard = WeatherDashboard.new
    @countries = CS.countries.sort_by { |_key, value| value }.map { |k, v| [v, k.to_s] }
  end

  def create
    @weather_dashboard = WeatherDashboard.new(weather_dashboard_params)
    @weather_dashboard.user = current_user
    if @weather_dashboard.save
      redirect_to weather_dashboards_path
    else
      @countries = CS.countries.sort_by { |_key, value| value }.map { |k, v| [v, k.to_s] }
      render :new
    end
  end

  def destroy
    @weather_dashboard = WeatherDashboard.where(user_id: current_user.id, city: params[:city]).first
    @weather_dashboard.destroy
    redirect_to weather_dashboards_path
  end

  def update_state_options
    states = CS.states(params[:country_code]).sort_by { |_key, value| value }.map { |k, v| [v, k.to_s] }
    states.unshift(['Select state', ''])
    cities = [['Select city', '']]

    render json: { states: states, cities: cities }, status: :ok
  end

  def update_city_options
    cities = CS.cities(params[:state_code], params[:country_code]).map { |i| [i, i] }
    cities.unshift(['Select city', ''])

    render json: { cities: cities }, status: :ok
  end

  private

  def weather_dashboard_params
    params.require(:weather_dashboard).permit(:country, :state, :city, :forecast_days)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    { success: 'alert-success', error: 'alert-danger', warning: 'alert-warning',
      notice: 'alert-info' }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      msg_type += '-info' if msg_type == 'alert'
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible fade show m-2",
                                        role: 'alert') do
               concat content_tag(:button, '', class: 'btn-close', data: { bs_dismiss: 'alert' })
               concat message
             end)
    end
    nil
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/weather_dashboards_helper.rb
module WeatherDashboardsHelper
end

app/views/home/index.html.erb
<div class="container text-center mt-5">
  <h1>Get Your Cities weather forecast.</h1>
  <p>Add weather card to dashboard and your good to go.<br/><em><b>Sign In</b> to get started</em></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetWeather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'shared/header' %>
      <%= render 'shared/alert' %>
    </header>
    <main>
      <div class="ms-5 me-5 mt-3">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/shared/_alert.html.erb
<%= flash_messages%>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'GetWeather', root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Add Weather Card', new_weather_dashboard_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= button_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-link btn-to-link-navbar' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path , class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Log In',  new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/weather_dashboards/_weather_card.html.erb
<div class="weatherInfo card w-100 border-0">
  <div class="card-body text-white">
    <div class="d-flex justify-content-between align-items-start">
      <div>
        <p class="mb-0"><%= location["name"] %>, <%= location["region"] %>, <%= location["country"] %></p>
        <p><%= Time.at( location["localtime_epoch"] ).strftime("%A, %B %d, %Y | %H:%M%p") %></p>
      </div>
      <div class="">
        <%= button_to 'Delete', weather_dashboard_path(id: 1, city: city), method: :delete, class: 'btn btn-outline-light' %>
      </div>
    </div>
    <div class="row py-4">
      <div class="col-md-7 d-flex  mx-auto">
        <div class="me-4"><img src="<%= weather_current["condition"]["icon"]%>" width="50px" class="mb-4"><p><%= weather_current["condition"]["text"]%></p></div>
        <div class="d-flex"><h1><%= weather_current["temp_c"]%></h1>°<span class="text-decoration-underline ms-1">C</span></div>
      </div>
      <div class="col-md-4">
        <p class="mb-2">Humidity :<span class="fw-500 ps-2"><%= weather_current["humidity"]%>%</span></p>
        <p class="mb-2">Wind  :<span class="fw-500 ps-2"><%= weather_current["wind_kph"]%> kmph</span></p>
        <p class="mb-2">Feels like: <span class="fw-500 ps-2"><%= weather_current["feelslike_c"]%>°</span></p>
      </div>
    </div>
    <div class="weather-grid weather-grid-top">
      <div class="weather-card mb-4">
        <img src="<%= weather_forecast_today["hour"][10]["condition"]["icon"]%>" width="35px" class="mb-3">
        <div>
            <div><%= weather_forecast_today["hour"][10]["temp_c"]%>°</div>
          <div>10:00 AM</div>
        </div>
      </div>
      <div class="weather-card mb-4">
        <img src="<%= weather_forecast_today["hour"][17]["condition"]["icon"]%>" width="35px" class="mb-3">
        <div class="temps">
          <div>
            <div><%= weather_forecast_today["hour"][17]["temp_c"]%>°</div>
            <div>05:00 PM</div>
          </div>
        </div>
      </div>
    </div>
    <div class="weather-grid weather-hover">
      <% if weather_forecast_future.present? %>
        <% weather_forecast_future.each do |forecast| %>
          <div class="weather-card">
            <p class="fw-500  mb-1"><%= Time.at( forecast["date_epoch"] ).strftime("%a") %></p>
            <img src="<%= forecast["day"]["condition"]["icon"] %>" width="35px" class="mb-1">
            <div class="d-flex justify-content-around mb-2">
              <div><%= forecast["day"]["maxtemp_c"] %>°</div>
              <div><%= forecast["day"]["mintemp_c"] %>°</div>
            </div>
            <div class="d-flex justify-content-around mb-2">
              <div><img src="<%= forecast["hour"][10]["condition"]["icon"] %>"  width="25px"></div>
              <div>10:00 AM</div>
            </div>
            <div class="d-flex justify-content-around mb-2">
              <div><img src="<%= forecast["hour"][17]["condition"]["icon"] %>" width="25px"></div>
              <div>05:00 PM</div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/weather_dashboards/index.html.erb
<% if @all_cities_weather.present? %>
  <h3 class>Your Weather Cards</h3><hr/>
<div class="row">
  <% @all_cities_weather.each do |city, weather_data| %>

      <div class="col-md-6 col-sm-12 col-lg-6  mb-3">
        <%= render partial: 'weather_card',
                    locals: { location: weather_data["location"], weather_current: weather_data["current"],
                              weather_forecast_today: weather_data["forecast"]["forecastday"].first,
                              weather_forecast_future: weather_data["forecast"]["forecastday"][1..-1],
                              city: city } %>
      </div>

  <% end %>
 </div>
<% else %>
  <div class="m-5 text-center">
    <h5>We don't find any weather card add to you account.</h5>
    <p>Get start by adding one
      <%= link_to 'Add Weather Card', new_weather_dashboard_path %>
    </p>
  </div>
<% end %>

<script>
  $(document).ready(function(){
    setInterval(() => {
      window.location.reload();
    }, 60000);
  });
</script>

app/views/weather_dashboards/new.html.erb
<%= form_with model: @weather_dashboard do |wd| %>

      <% if @weather_dashboard.errors.any? %>
        <div class="m-2">
          <div id="error_explanation" data-turbo-cache="false">
            <h2>
              <%= I18n.t("errors.messages.not_saved",
                        count: @weather_dashboard.errors.count,
                        resource: @weather_dashboard.class.model_name.human.downcase)
              %>
            </h2>
            <ul  class="text-danger">
              <% @weather_dashboard.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>

      <%end%>
      <h2 class="text-center mt-4 mb-4">Add Weather Card</h2>
      <div class="row justify-content-center">
        <div class="col-md-6">
          <div class="form-group mb-2">
          <%= wd.select :country, @countries, { selected: @weather_dashboard.country, include_blank: 'Select country' }, { class: 'form-select' } %>
          </div>
          <div class="form-group mb-2">
          <%= wd.select :state, [], { selected: @weather_dashboard.state, include_blank: 'Select state' }, { class: 'form-select' } %>
          </div>
          <div class="form-group mb-2">
          <%= wd.select :city, [], { selected: @weather_dashboard.city, include_blank: 'Select city' }, { class: 'form-select' } %>
          </div>
          <div class="form-group mb-2">
          <%= wd.select :forecast_days, Array(1..7), { selected: @weather_dashboard.forecast_days, include_blank: 'Select days of forecast' }, { class: 'form-select' } %>
          </div>
          <%= wd.submit 'Save Weather Card', { class: 'btn btn-outline-info mt-2' }%>
        </div>
      </div>
<% end %>

<script>
  $( document ).ready(function() {
    $('#weather_dashboard_country').on('change', function() {
      $.ajax({
        method: "GET",
        dataType: "JSON",
        url: "<%= update_state_options_weather_dashboards_path %>",
        data: { country_code: $(this).val() }
      }).done(function( data ) {
        updateOptions($("#weather_dashboard_state"), data.states)
        updateOptions($("#weather_dashboard_city"), data.cities)
      }).fail(function(error) {
        console.error(error)
      });
    });

    $('#weather_dashboard_state').on('change', function() {
      let country_code = $('#weather_dashboard_country').val();

      $.ajax({
        method: "GET",
        dataType: "JSON",
        url: "<%= update_city_options_weather_dashboards_path %>",
        data: { country_code: country_code, state_code: $(this).val() }
      }).done(function( data ) {
        updateOptions($("#weather_dashboard_city"), data.cities)
      }).fail(function(error) {
        console.error(error)
      });
    });

    function updateOptions(selectField, options){
      selectField.empty();
      options.forEach( function(option) {
        selectField.append($("<option></option>").attr("value", option[1]).text(option[0]));
      });
    }
  });
</script>